#!/bin/bash

set -e

# Create sshd daemon
echo "Creating sshd daemon"
mkdir -p /opt/gitlab/sv/sshd/supervise /opt/gitlab/sv/sshd/log/supervise
mkfifo /opt/gitlab/sv/sshd/supervise/ok /opt/gitlab/sv/sshd/log/supervise/ok
printf "#!/bin/sh\nexec 2>&1\numask 077\nexec /usr/sbin/sshd -D -f /assets/sshd_config -e" > /opt/gitlab/sv/sshd/run
printf "#!/bin/sh\nexec svlogd -tt /var/log/gitlab/sshd" > /opt/gitlab/sv/sshd/log/run
chmod a+x /opt/gitlab/sv/sshd/run /opt/gitlab/sv/sshd/log/run

# Remove current gitlab.rb file
echo "Removing current gitlab.rb file"
rm -f /etc/gitlab/gitlab.rb

# Patch omnibus package
echo "Patching omnibus package"
sed -i "s/external_url 'GENERATED_EXTERNAL_URL'/# external_url 'GENERATED_EXTERNAL_URL'/" /opt/gitlab/etc/gitlab.rb.template
sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/gitlab/recipes/show_config.rb
sed -i "s/\/etc\/gitlab\/gitlab.rb/\/assets\/gitlab.rb/" /opt/gitlab/embedded/cookbooks/gitlab/recipes/config.rb

# Set install type to docker
echo "Setting installation type to Docker"
echo 'gitlab-docker' > /opt/gitlab/embedded/service/gitlab-rails/INSTALLATION_TYPE

# Create groups
echo "Creating groups"

groupadd_if_not_exist()
{
	group=$1
  group_name=$2

  if ! grep -q "$group" /etc/group ; then
      echo "Adding group $group named $group_name"
      groupadd -g $group $group_name
  else
      echo "The group $group named $group_name already exists."
  fi
}

groupadd_if_not_exist 1007 git
groupadd_if_not_exist 1006 gitlab-www
groupadd_if_not_exist 1005 gitlab-redis
groupadd_if_not_exist 1004 gitlab-psql
groupadd_if_not_exist 1003 mattermost
groupadd_if_not_exist 1002 registry
groupadd_if_not_exist 1001 gitlab-prometheus
groupadd_if_not_exist 1000 gitlab-consul

# Create accounts
echo "Creating accounts"
useradd -m -u 1007 -g 1007 -m -s /bin/sh -d /var/opt/gitlab git
useradd -m -u 1006 -g 1006 -m -s /bin/false -d /var/opt/gitlab/nginx gitlab-www
useradd -m -u 1005 -g 1005 -m -s /bin/false -d /var/opt/gitlab/redis gitlab-redis
useradd -m -u 1004 -g 1004 -m -s /bin/sh -d /var/opt/gitlab/postgresql gitlab-psql
useradd -m -u 1003 -g 1003 -m -s /bin/sh -d /var/opt/gitlab/mattermost mattermost
useradd -m -u 1002 -g 1002 -m -s /bin/sh -d /var/opt/gitlab/registry registry
useradd -m -u 1001 -g 1001 -m -s /bin/sh -d /var/opt/gitlab/prometheus gitlab-prometheus
useradd -m -u 1000 -g 1000 -m -s /bin/sh -d /var/opt/gitlab/consul gitlab-consul
